#DockerCompose 버전 명시
version: "3.7"

services:
  gate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:8080"
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gate
